/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NonAuthenticatedImport } from './routes/_non-authenticated'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedManagementUnitManagementUnitIdImport } from './routes/_authenticated/management-unit.$managementUnitId'

// Create Virtual Routes

const NonAuthenticatedSignUpLazyImport = createFileRoute(
  '/_non-authenticated/sign-up',
)()

// Create/Update Routes

const NonAuthenticatedRoute = NonAuthenticatedImport.update({
  id: '/_non-authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const NonAuthenticatedSignUpLazyRoute = NonAuthenticatedSignUpLazyImport.update(
  {
    path: '/sign-up',
    getParentRoute: () => NonAuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_non-authenticated/sign-up.lazy').then((d) => d.Route),
)

const AuthenticatedManagementUnitManagementUnitIdRoute =
  AuthenticatedManagementUnitManagementUnitIdImport.update({
    path: '/management-unit/$managementUnitId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_non-authenticated': {
      id: '/_non-authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonAuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_non-authenticated/sign-up': {
      id: '/_non-authenticated/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof NonAuthenticatedSignUpLazyImport
      parentRoute: typeof NonAuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/management-unit/$managementUnitId': {
      id: '/_authenticated/management-unit/$managementUnitId'
      path: '/management-unit/$managementUnitId'
      fullPath: '/management-unit/$managementUnitId'
      preLoaderRoute: typeof AuthenticatedManagementUnitManagementUnitIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedIndexRoute,
    AuthenticatedManagementUnitManagementUnitIdRoute,
  }),
  NonAuthenticatedRoute: NonAuthenticatedRoute.addChildren({
    NonAuthenticatedSignUpLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_non-authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/management-unit/$managementUnitId"
      ]
    },
    "/_non-authenticated": {
      "filePath": "_non-authenticated.tsx",
      "children": [
        "/_non-authenticated/sign-up"
      ]
    },
    "/_non-authenticated/sign-up": {
      "filePath": "_non-authenticated/sign-up.lazy.tsx",
      "parent": "/_non-authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/management-unit/$managementUnitId": {
      "filePath": "_authenticated/management-unit.$managementUnitId.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
