/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DefaultImport } from './routes/_default'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as DefaultSignInImport } from './routes/_default/sign-in'
import { Route as AuthenticatedManagementUnitDashboardImport } from './routes/_authenticated/management-unit-dashboard'

// Create Virtual Routes

const DefaultSignUpLazyImport = createFileRoute('/_default/sign-up')()

// Create/Update Routes

const DefaultRoute = DefaultImport.update({
  id: '/_default',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const DefaultSignUpLazyRoute = DefaultSignUpLazyImport.update({
  path: '/sign-up',
  getParentRoute: () => DefaultRoute,
} as any).lazy(() =>
  import('./routes/_default/sign-up.lazy').then((d) => d.Route),
)

const DefaultSignInRoute = DefaultSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => DefaultRoute,
} as any)

const AuthenticatedManagementUnitDashboardRoute =
  AuthenticatedManagementUnitDashboardImport.update({
    path: '/management-unit-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/management-unit-dashboard': {
      id: '/_authenticated/management-unit-dashboard'
      path: '/management-unit-dashboard'
      fullPath: '/management-unit-dashboard'
      preLoaderRoute: typeof AuthenticatedManagementUnitDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_default/sign-in': {
      id: '/_default/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof DefaultSignInImport
      parentRoute: typeof DefaultImport
    }
    '/_default/sign-up': {
      id: '/_default/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof DefaultSignUpLazyImport
      parentRoute: typeof DefaultImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedManagementUnitDashboardRoute,
    AuthenticatedIndexRoute,
  }),
  DefaultRoute: DefaultRoute.addChildren({
    DefaultSignInRoute,
    DefaultSignUpLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_default"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/management-unit-dashboard",
        "/_authenticated/"
      ]
    },
    "/_default": {
      "filePath": "_default.tsx",
      "children": [
        "/_default/sign-in",
        "/_default/sign-up"
      ]
    },
    "/_authenticated/management-unit-dashboard": {
      "filePath": "_authenticated/management-unit-dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_default/sign-in": {
      "filePath": "_default/sign-in.tsx",
      "parent": "/_default"
    },
    "/_default/sign-up": {
      "filePath": "_default/sign-up.lazy.tsx",
      "parent": "/_default"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
